import type {
  ScrollScrubScene,
  ScrollScrubTheme,
} from "@/components/scroll-scrub/scroll-scrub";

export const scrollScrubTheme: ScrollScrubTheme = {
  accent: "#C9963C",
  background: "#F7F1E4",
  ink: "#3B2A20",
  muted: "#8A7860",
};

export const scrollScrubScenes: ScrollScrubScene[] = [
  {
    id: "scene-01",
    label: "곡물",
    kicker: "Chapter 01",
    title: "아홉 가지 좋은 곡물",
    body: "귀리, 현미, 백태, 보리, 찰현미, 밀, 멥쌀, 흑미, 서리태. 아홉 가지 곡물이 오트케어 그레인 한 봉지에 모입니다.",
    poster: "/assets/world/scene-01-poster.png",
    mobilePoster: "/assets/world/scene-01-mobile-poster.png",
    clip: "/assets/world/scene-01.mp4",
    mobileClip: "/assets/world/scene-01-mobile.mp4",
    tags: ["50g 한 봉지"],
    align: "left",
    scroll: 1.3,
  },
  {
    id: "scene-02",
    label: "식탁",
    kicker: "Chapter 02",
    title: "매일 아침, 우리 집 식탁으로",
    body: "바쁜 아침에도 챙기기 쉽게. 오트케어 한 봉지가 그대로 당신의 식탁 위로 옵니다.",
    poster: "/assets/world/scene-02-poster.png",
    mobilePoster: "/assets/world/scene-02-mobile-poster.png",
    clip: "/assets/world/scene-02.mp4",
    mobileClip: "/assets/world/scene-02-mobile.mp4",
    tags: ["뜯고 붓기만"],
    align: "right",
    scroll: 1.5,
  },
  {
    id: "scene-03",
    label: "완성",
    kicker: "Chapter 03",
    title: "물만 부어, 저어서",
    body: "따뜻한 물이나 우유를 붓고 30초만 저으면 끝. 좋은 원료를 그대로 마십니다.",
    poster: "/assets/world/scene-03-poster.png",
    mobilePoster: "/assets/world/scene-03-mobile-poster.png",
    clip: "/assets/world/scene-03.mp4",
    mobileClip: "/assets/world/scene-03-mobile.mp4",
    tags: ["30초 완성"],
    align: "left",
    scroll: 1.5,
  },
  {
    id: "scene-04",
    label: "오트케어",
    kicker: "Chapter 04",
    title: "완벽한 한 끼, 오트케어",
    body: "골고루, 든든하게, 매일 다른 맛으로. 바쁜 일상에도 놓치지 않는 균형 잡힌 한 끼.",
    poster: "/assets/world/scene-04-poster.png",
    mobilePoster: "/assets/world/scene-04-mobile-poster.png",
    clip: "/assets/world/scene-04.mp4",
    mobileClip: "/assets/world/scene-04-mobile.mp4",
    tags: ["다섯 가지 맛"],
    align: "right",
    scroll: 1.0,
  },
];
